# project_oracle/docker-compose.yml
version: '3.8'

# This file defines the services that make up your application.
# For now, we only have one service: our FastAPI API.
# The database (Supabase) runs in the cloud and is not defined here.

services:
  # This is the name of our service. We can call it 'api'.
  api:
    # 'build: .' tells Docker Compose to look for a Dockerfile in the current directory
    # and build an image from it.
    build: .
    ports:
      # This maps port 8000 on your local machine to port 8000 inside the container.
      # This is how you access the API at http://localhost:8000.
      - "8000:8000"
    env_file:
      # This tells Docker Compose to load environment variables from the .env file
      # and make them available to the application inside the container.
      - .env
    # 'restart: unless-stopped' ensures the container will automatically restart
    # if it crashes, unless you manually stop it.
    restart: unless-stopped